# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce814288b2fb09de985dc45b6b8dd1e4a174f8587836be5fd40741a21cc2a9427ee3f21ca5b4fe08ea301abadf8c1925ce688fcd02589eb6521a0d823c6626d3

test:
  secret_key_base: 37fcad17350e67b3b3473742bac364df8fc0cba725b9c11483507ab1379f2e59ea970e8a150591fb359e431b4f19a4b4e7816684425e9c638a12831a04c8b723

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
